Ticker = "5m"

[Email]
Host = "smtp.mailgun.org"
Port = 587
User = ""
Pass = ""
Display = "Robot"
From = ""
To = ["you@yourcompany.com"]
Subject = "Journald diff"

https://en.wikipedia.org/wiki/Syslog#Severity_level
[Services.hfast]
severity = 7
